name: Metrics
on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: [self-hosted, macOS]
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          user: shivansh052k
          token: ${{ secrets.GITHUB_TOKEN }}

          template: classic
          filename: github-metrics.svg

          base: header, activity, community, repositories
          config_timezone: America/New_York

          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_charts: yes

          plugin_stars: yes
          plugin_followup: yes
